In [8]:
import pandas as pd 
import matplotlib as plt

In [12]:
df = pd.DataFrame()

In [15]:
df = pd.read_excel('COVIDDATA.xlsx')

In [16]:
df

,iso_code,continent,country,date,total_cases,new_cases,total_deaths,new_deaths,total_cases_per_million,total_deaths_per_million,...,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,0.126,NaN,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,0.5,64.83,0.511
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,0.126,NaN,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,0.5,64.83,0.511
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,0.126,NaN,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,0.5,64.83,0.511
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,0.126,NaN,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,0.5,64.83,0.511
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,0.126,NaN,...,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,0.5,64.83,0.511
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155182,ZWE,Africa,Zimbabwe,2022-01-12,224433.0,1433.0,5215.0,35.0,14870.823,345.543,...,1.882,1899.775,21.4,307.846,1.82,1.6,30.7,1.7,61.49,0.571
155183,ZWE,Africa,Zimbabwe,2022-01-13,225084.0,651.0,5222.0,7.0,14913.958,346.007,...,1.882,1899.775,21.4,307.846,1.82,1.6,30.7,1.7,61.49,0.571
155184,ZWE,Africa,Zimbabwe,2022-01-14,225637.0,553.0,5238.0,16.0,14950.599,347.067,...,1.882,1899.775,21.4,307.846,1.82,1.6,30.7,1.7,61.49,0.571
155185,ZWE,Africa,Zimbabwe,2022-01-15,225637.0,0.0,5238.0,0.0,14950.599,347.067,...,1.882,1899.775,21.4,307.846,1.82,1.6,30.7,1.7,61.49,0.571
155186,ZWE,Africa,Zimbabwe,2022-01-16,226078.0,441.0,5247.0,9.0,14979.820,347.664,...,1.882,1899.775,21.4,307.846,1.82,1.6,30.7,1.7,61.49,0.571

Creating Smaller Dataframes to distribute and analize contextual data 
Given data set 
Italy, Portugal, UK, Mexico and Canada

This is for distribution of Data with members

In [27]:
portugal = df[(df['country']=='Portugal')]

In [29]:
portugal.to_csv('PortugalDATA.csv')

In [32]:
Canada = df[df['country']=='Canada']

In [34]:
Canada.to_csv('CanadaDATA.csv')

In [36]:
Italy  = df[df['country']=='Italy']

In [37]:
Italy.to_csv('ItalyDATA.csv')

In [40]:
UnitedKingdom = df[df['country']=='United Kingdom']

In [44]:
UnitedKingdom.to_csv('UnitedKingdomDATA.csv')

In [45]:
Mexico = df[df['country']=='Mexico']

In [46]:
Mexico.to_csv('MexicoDATA.csv')

In [47]:
Portugal = df[df['country']=='Portugal']

In [48]:
Portugal.to_csv('Portugal.csv')